language: python

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: generic
      env: PYTHON=37
    - os: osx
      osx_image: xcode10.2
      language: generic
      env: PYTHON=36
    - os: osx
      osx_image: xcode10.2
      language: generic
      env: PYTHON=27
    - os: linux
      python: 3.7
      dist: xenial
    - python: 3.6
    - python: 2.7

cache: pip
install:
  - pip install -r requirements.txt
  - pip install pytest
script:
  - pytest
  # - flake8 HARK
